### ISSUE TITLE
Removing a plugin doesn't reset Control menu in track popup

### ISSUE THREAD

**Issue by milkmiruku** [j3ffhubb/musikernel#11]
If I add a plugin to a track, say MK Delay, select it in the plugin menu on that tracks popup on Sequencer, the Control menu is populated with paramaters. Remove that plugin by setting to None on Plugin Rack, and the popup now displays "Plugin: None" but "Control: Dry Delay" with the other paramaters still available for selection. 

Changing "Plugin" in the popup to one of the other "None"s clears this, though after re-adding the plugin, the Control menu isn't repopulated again, regardless of what plugin is added.

**Comment by j3ffhubb** [comment]
Good catch, I will fix it.
