### ISSUE TITLE
'In Use:' menu tick value only visible when menu is clicked on.

### ISSUE THREAD

**Issue by milkmiruku** [j3ffhubb/musikernel#12]
Having to click on the menu to see the value doesn't make sense to me. If it's a boolean, maybe something other than a menu would be more appropriate.

In general, I'm not entirely sure what these menus reflect. If I set plugin to None, no tick. If I click away then click the popup open again (then click the In Use menu), there is a tick.

**Comment by j3ffhubb** [comment]
The purpose of the "In Use" menu is to allow you to quickly see and open controls as automation lanes (when EditMode=Automation) that are already in use.  It's meant to be a time saver vs. having to scroll through a big menu of controls in plugins like in Way-V or Euphoria when you're only using 2 or 3 of them.

`In general, I'm not entirely sure what these menus reflect.`  Forgive me if I'm misunderstanding your question, but those controls are only valid when you toggle to automation mode by clicking the sequencer menu button, or using the CTRL+E hotkey.  Then you can draw automation points with the draw tool, erase them with the erase tool, perform right-click context menu actions, etc...  Of course, you'll only be able to draw automation on tracks that have a plugin and control selected from the aforementioned menus.  If that's not what you meant, let me know.

**Comment by j3ffhubb** [comment]
I believe this has been adequately answered, if not, feel free to re-open the issue.
