### ISSUE TITLE
Hitting 'Cancel' on the Hardware Settings dialog restarts MK anyway

### ISSUE THREAD

**Issue by milkmiruku** [j3ffhubb/musikernel#13]
Might there be a reason it does this?

**Comment by j3ffhubb** [comment]
Yes, the audio engine has to be killed before the hardware dialog launches, otherwise Portaudio can't enumerate all of the audio devices.  Long story short, the sanest and most cross-platform way to restart the audio engine is to relaunch MusiKernel.
