### ISSUE TITLE
With a full screen height menu, cannot scroll upward

### ISSUE THREAD

**Issue by milkmiruku** [j3ffhubb/musikernel#14]
When using the Way-V synth, clicking the Control menu in the track popup gives a menu that is the full height of my screen. Hovering over the bottom most item scrolls the menu down to show other items, but hovering on the topmost item doesn't do the reverse. I have to click an item near the top, click off, then click the menu again and use the fact that the menu has recentered on the selected item to see items that were further up again.

**Comment by j3ffhubb** [comment]
I think this is a regression in Qt5, they broke a lot of things related to QMenu in 5.5.0.  (I assume you have Qt5 >= 5.5.0 installed, let me know if not).  The mouse scrollwheel also used to work, but now it doesn't.

I'll investigate further, but for now you can work around the problem by clicking on the Control menu and then using the up and down arrow keys on your keyboard to select the control.
