### ISSUE TITLE
GUI: missing play buttons

### ISSUE THREAD

**Issue by rghvdberg** [j3ffhubb/musikernel#6]
>$ lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa

# 

 >dpkg -l | grep musikernel2
>ii  musikernel2                                 16.01.1                                             amd64        MusiKernel is digital audio workstations (DAWs), instrument and effect plugins.

kxstudio repos installed
cinnamon desktop and numix theme installed

As you can see on the screenshot the play/stop/record buttons are missing
![schermafdruk van 2016-01-05 11 51 14](https://cloud.githubusercontent.com/assets/10710663/12113784/6ae4fb92-b3a5-11e5-852b-f64d286fb3d1.png)

**Comment by j3ffhubb** [comment]
Hello, thanks for reporting.  Is this immediately after installing, or have you opened an edited version of the theme?  Also, did you install the Debian or Ubuntu package from my Github page, or did the package come from somewhere else?

**Comment by rghvdberg** [comment]
I installed the ubuntu package from github today and noticed it when suddenly the (empty) project started playing. Must accidentally have clicked the invisible play button. Then I realised that I couldn't find start/stop ...

I didn't edit the theme.
Reloaded the default theme just now. No change.

**Comment by j3ffhubb** [comment]
I have a fix in progress right now.  It's a packaging bug, Ubuntu bundles libqt5svg5 with it's qt5 package, and Mint and Debian do not, so they silently fail to load svg assets.

Here is a manual fix until I can get the packages sorted out:

```
sudo apt-get install libqt5svg5
```

**Comment by rghvdberg** [comment]
Confirmed

![musikernel 2 - -home-rob-musikernel2-default-project-default musikernel2_004](https://cloud.githubusercontent.com/assets/10710663/12138429/396495b4-b459-11e5-93b9-4972b1a547e0.png)
