### ISSUE TITLE
GUI: overlapping text labels in plugins

### ISSUE THREAD

**Issue by rghvdberg** [j3ffhubb/musikernel#7]
>$ lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa

# 

 >dpkg -l | grep musikernel2
>ii  musikernel2                                 16.01.1                                             amd64        MusiKernel is digital audio workstations (DAWs), instrument and effect plugins.

kxstudio repos installed
Cinnamon desktop with numix theme

The labels at "Oscillator" , "Distortion" etc show overlaps making some labels even unreadable

![schermafdruk van 2016-01-05 11 56 20](https://cloud.githubusercontent.com/assets/10710663/12113727/137eb834-b3a5-11e5-96ec-7dcc67236f14.png)

**Comment by j3ffhubb** [comment]
This is probably part of the other issue you reported.  MusiKernel uses Qt-CSS for the UI theme, but it seems like the stylesheet doesn't finish parsing.  I'll install Linux Mint Cinnamon in a VM to see if I can replicate the issue, but here are some things to try:

```
# Ensure that the default theme is used
rm ~/musikernel2/config/default-style.txt
```

```
ls /usr/lib/musikernel2/themes/default/
```

which should show all of these files:

```
default.pytheme  knob-fg.png       rec_checked.svg  spinbox-down.png
draw.svg         mute-off.png      record-off.png   spinbox-up.png
drop-down.png    mute-on.png       record-on.png    split.svg
erase.svg        palette.json      rec.svg          stop_checked.svg
h-fader.png      play_checked.svg  select.svg       stop.svg
hide-off.png     play.svg          slice.svg        v-fader.png
hide-on.png      power-off.png     solo-off.png
knob-bg.png      power-on.png      solo-on.png
```

**Comment by rghvdberg** [comment]
Did the above.
No change.
Hope we can work this out. It seems like an interesting application. 
I will test in Windows 10 too :-)

**Comment by j3ffhubb** [comment]
I've confirmed that my forthcoming fix for #6 also fixes this bug

**Comment by j3ffhubb** [comment]
The Ubuntu and Debian packages I just uploaded fix the issue, thanks again for reporting it :-)

**Comment by rghvdberg** [comment]
purged musikernel2 and installed new package
problem still persists 
![musikernel 2 - -home-rob-musikernel2-default-project-default musikernel2_003](https://cloud.githubusercontent.com/assets/10710663/12138411/0bda320c-b459-11e5-9106-5db9008a5980.png)

**Comment by j3ffhubb** [comment]
Oops, sorry about that.  I'm not sure what I was looking at when I thought it was fixed, I had a handful of VM windows open.

I can reproduce the problem in Linux Mint 17.3 (Cinnamon or Mate desktop), but the groupbox labels look as expected in Ubuntu 14.04.3, Debian 8.3, Fedora 23, Mac OS X El Capitan and Windows 7.  I'll experiment with the stylesheet to see if I can find a workaround, but this could be something that the Linux Mint folks will have to fix.

**Comment by j3ffhubb** [comment]
It appears that somehow Linux Mint is misreporting their font height as zero, causing the CSS unit "ex" to always be zero.  This should be easy enough to work around, I'll fix it tonight after work.

**Comment by j3ffhubb** [comment]
I re-uploaded the Ubuntu package with the fix, try it again.  I'll wait until you've confirmed it's working before closing the bug again.

I really appreciate the bug reports, I shudder to think how many people may have tried MusiKernel on Linux Mint and didn't bother reporting the bugs :-)

**Comment by j3ffhubb** [comment]
I'm confident this is fixed, I'm going to go ahead and close the issue.  Thanks again.
